### ISSUE TITLE
Moreutils breaks HiveOS installation

### ISSUE THREAD

**Issue by Taifuuni** [Akisoft41/qubic-hive-twice#2]
'Apt install moreutils' breaks current version of HiveOS and cannot be repaired without reflashing HDD/SSD/USB stick.

**Comment by Taifuuni** [comment]
Tested little bit more. On fresh HiveOS 0.6-225 beta image, installing moreutils works correct and does not break HiveOS.

However if user has previously installed EloWord's Qubic Miner, there is a possibility that the users apt sources.list has an additional source called "deb http://archive.ubuntu.com/ubuntu jammy main". This is because in EloWord instructions, this command is instructed to be run.
![image](https://github.com/Akisoft41/qubic-hive-twice/assets/1225532/439c6ad6-e183-4b10-9643-432df1b4a948)

If this source is existing and user tries to install moreutils with apt, it will remove a lot of essential HiveOS packages and will brick the OS.

This is normal install after fresh HiveOS install:
![image](https://github.com/Akisoft41/qubic-hive-twice/assets/1225532/42502485-e36a-4812-9a0a-50c5894bcb7c)

If user has the additional apt source defined, installing moreutils will affect all these packages:
![image](https://github.com/Akisoft41/qubic-hive-twice/assets/1225532/d301a25b-358e-4c86-8fca-7aeb1bdac6a0)

To remedy this situation, I think you need to check for this additional source in the /etc/apt/sources.list file before installing moreutils with your script.

**Comment by Akisoft41** [comment]
Since HiveOS beta uses Ubuntu 20, there is no need to update the LibC...
